source 'http://localhost:9292'

gem 'rails', '3.2.12'

gem 'devise', '2.2.3'
gem 'omniauth', '1.1.4'
gem 'omniauth-github', '1.1.0'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3', '1.3.7'

gem 'jquery-rails', '2.2.1'

gem 'typus', '3.1.10'

gem 'rugged', '0.16.0'

gem 'github_api', '0.9.7'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails', '~> 3.2.3'
  gem 'uglifier', '>= 1.0.3'

  gem 'bootstrap-sass', '~> 2.3.1.0'
end

# Gems used for testing and development
group :test, :development do
  gem 'faker', '1.1.2'
end

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
